### ISSUE TITLE
Greg's Notebook does not open in the Github Viewer

### ISSUE THREAD

**Issue by apahl** [rdkit/UGM_2024#11]
The `What's New` Notebook gives an "Invalid Notebook" error in the Github viewer:

![image](https://github.com/user-attachments/assets/65af10f4-5ade-485b-8b95-82f89ac26b4f)

**Comment by greglandrum** [comment]
hmm, weird.
I will see if I can figure out what's going on.
Thanks for pointing this out.

**Comment by greglandrum** [comment]
@apahl it should work now. Please check though

**Comment by apahl** [comment]
Yes, it works now. Thanks a lot for the quick fix!
